services:
    _defaults:
        autowire: true
        public: false

    LoremIpsum\PermissionCheckerBundle\Model\PermissionCheckerInterface: '@LoremIpsum\PermissionCheckerBundle\Utils\PermissionChecker'

    LoremIpsum\PermissionCheckerBundle\Utils\PermissionChecker:

    LoremIpsum\PermissionCheckerBundle\Twig\PermissionExtension:
        tags: ['twig.extension']